function cost = optimize_EMG_kernel(self, params)

  %%%
  % returns the log-likelihood that a given rate function generated a given spike train
  % the rate function is generated by convolving a known extrinsic biological signal
  % with an exponentially-modified Gaussian kernel

  %% Produce an exponentially-modified Gaussian kernel

  bandwidth = 60; % seconds


end % cost_function
